os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - phpenv rehash
  - mysql -e 'create database matrix;'
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-text

cache:
  directories:
    - $HOME/.composer/cache/files

sudo: false

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

services:
  - mysql
